# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 428b52d96d5f814d8120fcf81cf5b599756966954213de76a539f016817ab119490d413d931426bb849c1886679eea75960cf95bfca6257a1d5c799c6a99d19b

test:
  secret_key_base: b3b0a40a52dbc78f63f3016cf05d8075794114888c372f98553daf97faeac3090c7947d3151a9da37fd6403139f61bf364d1bdf5cfd8f4a3ac5f11306440597d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
